### ISSUE TITLE
Conflict with minitest-reporters 1.1.17

### ISSUE THREAD

**Issue by leoarnold** [jeremyevans/minitest-hooks#14]
**Abstract:**  `minitest-hooks` 1.4.1 conflicts with `minitest-reporters` 1.1.17. It will work with the default reporter, but conflicts with other reporters are laid out in detail below.

**Problem:** Using any Ruby `~> 2.0` with

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'minitest', '5.10.3'
gem 'minitest-hooks', '1.4.1'
gem 'minitest-reporters', '1.1.17'
```

and the toy example

```ruby
# working.rb
require 'minitest/autorun'
require 'minitest/hooks/test'
require 'minitest/reporters'

Minitest::Reporters.use!

class Working < Minitest::Test
  include Minitest::Hooks

  def before_all
    # Simulate exception in before_all &block
    raise 'OMG'
  end

  def test_something
    assert 1 == 1
  end
end
```

yields

```shell
$ bundle exec ruby working.rb 
Started with run options --seed 7562

ERROR[:before_all, Working, 0.0006391889983206056]
 before_all#Working (0.00s)
RuntimeError:         RuntimeError: OMG
            working.rb:11:in `before_all'

  1/1: [=========================================================================================================================================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.00086s
1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
```

which is informative. **BUT** when I use `SpecReporter`

```ruby
# spec_reporter_conflict.rb 
require 'minitest/autorun'
require 'minitest/hooks/test'
require 'minitest/reporters'

Minitest::Reporters.use! [Minitest::Reporters::SpecReporter.new]

class SpecReporterConflict < Minitest::Test
  include Minitest::Hooks

  def before_all
    # Simulate exception in before_all &block
    raise 'OMG'
  end

  def test_something
    assert 1 == 1
  end
end
```

I get

```shell
$ bundle exec ruby spec_reporter_conflict.rb 
Started with run options --seed 9533

./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/reporters/spec_reporter.rb:46:in `record_print_status': undefined method `gsub' for :around_all:Symbol (NoMethodError)
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/reporters/spec_reporter.rb:31:in `record'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/minitest_reporter_plugin.rb:21:in `block in record'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/minitest_reporter_plugin.rb:20:in `each'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/minitest_reporter_plugin.rb:20:in `record'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:682:in `block in record'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:681:in `each'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:681:in `record'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-hooks-1.4.1/lib/minitest/hooks/test.rb:100:in `rescue in with_info_handler'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-hooks-1.4.1/lib/minitest/hooks/test.rb:68:in `with_info_handler'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:309:in `run'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:159:in `block in __run'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:159:in `map'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:159:in `__run'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:136:in `run'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:63:in `block in autorun'
```

**OR** when I use `HtmlReporter`

```ruby
# html_reporter_conflict.rb 
require 'minitest/autorun'
require 'minitest/hooks/test'
require 'minitest/reporters'

Minitest::Reporters.use! [Minitest::Reporters::HtmlReporter.new]

class HtmlReporterConflict < Minitest::Test
  include Minitest::Hooks

  def before_all
    # Simulate exception in before_all &block
    raise 'OMG'
  end

  def test_something
    assert 1 == 1
  end
end
```

I get

```shell
$ bundle exec ruby html_reporter_conflict.rb 
Emptying ./toy_example/test/html_reports
Writing HTML reports to ./toy_example/test/html_reports
There was an error writing the HTML report
This may have been caused by cancelling the test run
Use mode => :terse in the HTML reporters constructor to see less detail
./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/reporters/html_reporter.rb:176:in `+': nil can't be coerced into Integer (TypeError)
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/reporters/html_reporter.rb:176:in `block in summarize_suite'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/reporters/html_reporter.rb:172:in `each'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/reporters/html_reporter.rb:172:in `summarize_suite'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/reporters/html_reporter.rb:98:in `block in report'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/reporters/html_reporter.rb:97:in `each'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/reporters/html_reporter.rb:97:in `map'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/reporters/html_reporter.rb:97:in `report'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/minitest_reporter_plugin.rb:26:in `each'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-reporters-1.1.17/lib/minitest/minitest_reporter_plugin.rb:26:in `report'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:687:in `each'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:687:in `report'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:141:in `run'
        from ./toy_example/vendor/bundle/ruby/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:63:in `block in autorun'
```

**Suspicion:** In the case of `SpecReporter`
* we have cause an exception in [minitest/hooks/test.rb#L74](https://github.com/jeremyevans/minitest-hooks/blob/1.4.1/lib/minitest/hooks/test.rb#L74)
* which will be caught in [L96](https://github.com/jeremyevans/minitest-hooks/blob/1.4.1/lib/minitest/hooks/test.rb#L96) - because that line catches absolutely everything
* by that time we passed [L92](https://github.com/jeremyevans/minitest-hooks/blob/1.4.1/lib/minitest/hooks/test.rb#L92) and set `@instance.name = :around_all`
* which will now throw the reporter out of whack in [L100](https://github.com/jeremyevans/minitest-hooks/blob/1.4.1/lib/minitest/hooks/test.rb#L100) because `:around_all` is a Symbol and therefore does not have a `gsub` method.

In the case of `HtmlReporter`, the reporter tries to access `test.time` which was never set:

```
#<HtmlReporterConflict:0x005587c69db9f0 @NAME=:around_all, @failures= #<Minitest::UnexpectedError: Unexpected exception>], @assertions=0>
```

In both cases the stack traces are not useful to the average Ruby coder. In a real world example, it is **absolutely unclear** that an exception occured in `before_all` - even more so because the `SpecReporter` stack trace contains `:around_all:Symbol` but we did not even use an `around_all` method.

**Workaround:** For anyone who finds this issue report and needs a quick fix, you could try:

```ruby
def before_all # or after_all or around_all
  # your code here
rescue => e
  puts "#{e.class} in #{self}: #{e.message}"
  exit 1
end
```

**Comment by jeremyevans** [comment]
Thanks for the report. The `test.time` issue appears to be the same issue as #13. The `@instance.name` can be set to a string instead of a symbol if that is what is expected. I should be able to work on a fix for both of these issues today.

**Comment by jeremyevans** [comment]
I've pushed a fix to this, can you please test it in your environment and see if it resolves your issues before I release a new gem?

**Comment by leoarnold** [comment]
**Results:**

```shell
$ bundle exec ruby working.rb ; echo "Command exited $?"
Started with run options --seed 49134

ERROR["before_all", Working, 0.0006780529984098393]
 before_all#Working (0.00s)
RuntimeError:         RuntimeError: OMG
            working.rb:13:in `before_all'

  1/1: [=========================================================================================================================================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.00097s
1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
Command exited 1



$ bundle exec ruby spec_reporter_conflict.rb ; echo "Command exited $?"
Started with run options --seed 28574

  before_all                                                     ERROR (0.00s)
RuntimeError:         RuntimeError: OMG
            spec_reporter_conflict.rb:12:in `before_all'


Finished in 0.00069s
1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
Command exited 1



$ bundle exec ruby html_reporter_conflict.rb ; echo "Command exited $?"
Emptying ./toy_example/test/html_reports
Writing HTML reports to ./toy_example/test/html_reports
Command exited 1
```

The last one (`HtmlReporter`) is quiet _as expected_ and will log the error in the HTML report:

![screenshot_20170906_204623](https://user-images.githubusercontent.com/4201235/30128921-975bace0-9344-11e7-8359-0123c0f784c5.png)

Note: While the log message is definitely helpful, the name of the failing test is reported as `around_all` :-/

I guess every reporter might have it's particular problems (and they might change with the versions of the reporters gem) but for the cases we have covered here I'd say this is very helpful and a major improvement.

**Comment by jeremyevans** [comment]
We don't necessarily need to use `around_all` (or similar) as the name.  We could probably include the name of the class to make it more obvious.

**Comment by jeremyevans** [comment]
OK, I've pushed another commit for more obvious names, and started testing the names with minitest/test in addition to minitest/spec.  Can you please let me know if that improves things for you?

**Comment by leoarnold** [comment]
Still says `around_all`, now as `Working#around_all`

![screenshot_20170907_142606](https://user-images.githubusercontent.com/4201235/30163251-9a2b768c-93d8-11e7-89cb-a23eb1529010.png)

**Comment by jeremyevans** [comment]
I've pushed another commit, it should say `Working#before_all` now.  Can you confirm and let me know if that works for you?

**Comment by leoarnold** [comment]
Now it says `Working#after_all`
![screenshot_20170908_185901](https://user-images.githubusercontent.com/4201235/30222720-0d517680-94c8-11e7-80b6-83b59de7a1be.png)

**Comment by jeremyevans** [comment]
Looks like I need to handle that case as well.  I also should probably add tests for the name handling in the failure case.

**Comment by jeremyevans** [comment]
I think I've pushed a commit that will handle things correctly, as well as specs.  Can you test again?  Thanks for your continued help on this.

**Comment by leoarnold** [comment]
@jeremyevans I provided you with the whole specification of my environment including all necessary file in my very first post. You are perfectly capable of running your experiments yourself. Just use [RVM](http://rvm.io/) and [Bundler](http://bundler.io/). Bundler can even [fetch any commit](http://bundler.io/v1.12/git.html) in a gem-style fashion.

**Comment by jeremyevans** [comment]
@leoarnold Fair enough.  Thanks for your earlier help.
