### ISSUE TITLE
Rails 6 parallel testing causes NoMethodError

### ISSUE THREAD

**Issue by kazooiebombchu** [jeremyevans/minitest-hooks#16]
I'm currently using this gem with Rails 6 and using before_all methods to setup some expensive database setup. However with new rails parallel testing enabled this hook throws NoMethodError with following traceback:
```
Traceback (most recent call last):
	19: from -e:1:in `<main>'
	18: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	16: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	15: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	14: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	13: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	12: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
	11: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
	10: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
	 9: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:133:in `run'
	 8: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/testing/parallelization.rb:70:in `start'
	 7: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/testing/parallelization.rb:70:in `map'
	 6: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/testing/parallelization.rb:70:in `each'
	 5: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/testing/parallelization.rb:70:in `times'
	 4: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/testing/parallelization.rb:71:in `block in start'
	 3: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/testing/parallelization.rb:71:in `fork'
	 2: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/testing/parallelization.rb:82:in `block (2 levels) in start'
	 1: from /home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:960:in `run_one_method'
/home/kazooie/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/minitest-hooks-1.5.0/lib/minitest/hooks/test.rb:56:in `new': undefined method `name=' for nil:NilClass (NoMethodError)
```

Steps to reproduce:
* make new rails project
* install minitest-hooks gem
* require gem in `test/test_helper.rb` file and include hooks in `ActiveSupport::TestCase` test class.
* subclass any test from this and run with `rails test`.

Possible to fix this issue? If not then I need to refactor my before_all hooks to setup methods instead :/

**Comment by jeremyevans** [comment]
This appears to be a bug in ActiveSupport.  When enabling parallelization, they are not calling `with_info_handler` around the calling of `run_one_method`, which is what minitest does and what minitest-hooks requires.
