### ISSUE TITLE
minitest versions affecting test executions on .spec files (Version update issue)

### ISSUE THREAD

**Issue by harshwardhanedu** [jeremyevans/minitest-hooks#24]
****Issue :**** 

```
spec/examples/file_name_spec.rb:33:in `block (2 levels) in <main>': undefined method `context' for ClassNamespace:Class (NoMethodError)

 

    context 'context_title' do
    ^^^^^^^
Did you mean?  const_get
        from <ruby_path>/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/spec.rb:94:in `class_eval'
        from <ruby_path>/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/spec.rb:94:in `describe'
        from spec/examples/file_name_spec.rb:14:in `block in <main>'
        from <ruby_path>/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/spec.rb:94:in `class_eval'
        from <ruby_path>/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/spec.rb:94:in `describe'
        from spec/examples/file_name_spec.rb:5:in `<main>'
        
```
     
**Mentioning the versions in use while getting this issue**

- ruby 3.2.1
- minitest v2.19.0
- minitest-hooks v1.5.1
- minitest-spec-context v0.0.4

**Comment by harshwardhanedu** [comment]
I have misplaced this issue closing it .
Sorry for incontinency
