### ISSUE TITLE
How to correctlly use `around_all` with minitest?

### ISSUE THREAD

**Issue by foton** [jeremyevans/minitest-hooks#25]
I have on 2 test files (4 and  2 tests). Only later one (test/db_test_seeds_consistency_test.rb) uses `Minitest::Hooks` and look like
```
require "test_helper"
require "minitest/hooks/test"

class DbTestSeedsConsistencyTest < ActiveSupport::TestCase
  include Minitest::Hooks

  def around_all
    ApplicationRecord.transaction do
      Rails.logger.info("around_all 1")

      Rails.logger.info("around_all 2")
      p1=create(:auctify_sales_pack, title: "around_all")
      puts(p1.site.id)
      Rails.logger.info("around_all 3")
      super
      Rails.logger.info("around_all 4")
      raise ActiveRecord::Rollback
      Rails.logger.info("around_all 5")
    end
  end

  test "blank test" do
    Rails.logger.info("test 1")
    p2=create(:auctify_sales_pack, title: "test")
    puts(p2.site.id)
    Rails.logger.info("test 2")
  end

  test "another test" do
    Rails.logger.info("testB 1")
    p2=create(:auctify_sales_pack, title: "testB")
    puts(p2.site.id)
    Rails.logger.info("testB 2")
  end
end
```

when I run it as `PARALLEL_WORKERS=1 bundle exec rails test ` , I got  sucessfull results
```
Run options: -v --seed 61665

# Running:

DbTestSeedsConsistencyTest#test_blank_test = 0.01 s = .
DbTestSeedsConsistencyTest#test_another_test = 0.01 s = .
Auctify::MinimalBidsLadderlTypeTest#test_it_can_store_ranged_hash = 0.23 s = .
Auctify::MinimalBidsLadderlTypeTest#test_it_can_store_min_prices_as_strings = 0.09 s = .
Auctify::MinimalBidsLadderlTypeTest#test_it_can_store_min_prices_as_numbers = 0.09 s = .
Auctify::MinimalBidsLadderlTypeTest#test_it_can_store_min_prices_from_json = 0.09 s = .

Finished in 0.953083s, 7.3446 runs/s, 9.4430 assertions/s.
6 runs, 9 assertions, 0 failures, 0 errors, 0 skips
```

but when i run it through `PARALLEL_WORKERS=2 bundle exec rails test`, I got 

```
Running 6 tests in parallel using 2 processes
Run options: -v --seed 54491

# Running:

Auctify::MinimalBidsLadderlTypeTest#test_it_can_store_ranged_hash = 0.72 s = .
Auctify::MinimalBidsLadderlTypeTest#test_it_can_store_min_prices_as_strings = 0.72 s = .
Auctify::MinimalBidsLadderlTypeTest#test_it_can_store_min_prices_as_numbers = 0.72 s = .
Auctify::MinimalBidsLadderlTypeTest#test_it_can_store_min_prices_from_json = 0.74 s = .
.
(drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/server.rb:21:in `record': undefined method `klass' for nil:NilClass (NoMethodError)
	from (drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/drb/drb.rb:1684:in `perform_without_block'
	from (drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/drb/drb.rb:1640:in `perform'
	from (drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/drb/drb.rb:1729:in `block (2 levels) in main_loop'
	from (drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/drb/drb.rb:1725:in `loop'
	from (drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/drb/drb.rb:1725:in `block in main_loop'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:60:in `safe_record'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:53:in `perform_job'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:38:in `work_from_queue'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:27:in `block in start'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:15:in `fork'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:15:in `start'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization.rb:37:in `block in start'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization.rb:36:in `times'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization.rb:36:in `each'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization.rb:36:in `map'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization.rb:36:in `start'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelize_executor.rb:18:in `start'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.20.0/lib/minitest.rb:159:in `run'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.20.0/lib/minitest.rb:86:in `block in autorun'
(drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/server.rb:21:in `record': undefined method `klass' for nil:NilClass (NoMethodError)
	from (drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/drb/drb.rb:1684:in `perform_without_block'
	from (drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/drb/drb.rb:1640:in `perform'
	from (drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/drb/drb.rb:1729:in `block (2 levels) in main_loop'
	from (drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/drb/drb.rb:1725:in `loop'
	from (drbunix:/tmp/druby134329.0) /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/drb/drb.rb:1725:in `block in main_loop'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:60:in `safe_record'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:53:in `perform_job'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:38:in `work_from_queue'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:27:in `block in start'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:15:in `fork'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization/worker.rb:15:in `start'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization.rb:37:in `block in start'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization.rb:36:in `times'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization.rb:36:in `each'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization.rb:36:in `map'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelization.rb:36:in `start'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/testing/parallelize_executor.rb:18:in `start'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.20.0/lib/minitest.rb:159:in `run'
	from /home/foton/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.20.0/lib/minitest.rb:86:in `block in autorun'
DbTestSeedsConsistencyTest#test_blank_test = 0.00 s = E


Error:
DbTestSeedsConsistencyTest#test_blank_test:
RuntimeError: result not reported

    

rails test test/db_test_seeds_consistency_test.rb:38

DbTestSeedsConsistencyTest#test_another_test = 0.00 s = E


Error:
DbTestSeedsConsistencyTest#test_another_test:
RuntimeError: result not reported
    


rails test test/db_test_seeds_consistency_test.rb:44


Finished in 1.616075s, 4.3315 runs/s, 5.5690 assertions/s.
6 runs, 9 assertions, 0 failures, 2 errors, 0 skips
```

Using PostgreSQL.
What I am doing wrong? 
I want to do heavy load before all test in `test/db_test_seeds_consistency_test.rb` (alias `DbTestSeedsConsistencyTest`) and clean up DB after. Heavy load includes many models and relations.

**Comment by foton** [comment]
When I add third test to `DbTestSeedsConsistencyTest` and run it as `PARALLEL_WORKERS=2 bundle exec rails test` it stucks with 2 errors. 
Running it as `PARALLEL_WORKERS=3 bundle exec rails test` it stucks with 3 errors.
Running it as `PARALLEL_WORKERS=4 bundle exec rails test` it finishes with 3 errors.

**Comment by jeremyevans** [comment]
From the backtrace, the problem is in active_support's parallelization code.   It must be doing something that doesn't work with minitest-hooks.  I'm going to consider that a bug in active_support, not in minitest-hooks.  I'll consider a backwards compatible pull request that makes minitest-hooks works with active_support's parallelization code, but that's not something I plan to work on myself.
